.\" Process this file with groff -man -Tascii cittaserver.6
.TH CITTASERVER 6 "October 30, 1999"
.SH NAME
cittaserver \- the server application for the Cittadella/UX BBS
.SH SYNOPSIS
.B cittaserver
.RB [ "\-pvlfhV" ]
.RB [ "\-\-port=" PORT]
.RB [ "\-\-help" ]
.RB [ "\-\-version" ]
.SH DESCRIPTION
.B cittaserver
is the server application for Cittadella/UX, a realtime multiuser Bulletin
Board System.

See
.BR cittaclient (6)
for details on the Cittadella/UX client.
.SH OPTIONS
.TP
.I "\-p, \-\-port=PORT"
Listen on the port 
.I PORT
instead of the default port.
.TP
.I "\-h, \-\-help"
Print a short help text and then exit.
.TP
.I "\-V, \-\-version"
Print the version number to standard output and exit.
.SH FILES
.TP

.SH BUGS

.SH LICENCE

.SH AUTHOR
Marco Caldarelli <caldarel@science.unitn.it>
.br
Riccardo Vianello <vianello@chim.sns.it>
.PP
Thanks to all people who contributed:
.PP
.br

.br
.SH "SEE ALSO"
.BR cittaclient (6)
